# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b43ae7cadbccad3fd78ae952f675ff0cb58285ab2d0b82c36e5566ca24eec80901aa57694ff296afba004882ef740236d83e2b12f97dc9d049d9df3712283b0

test:
  secret_key_base: 75d4bf6f83368e4d85b1422e702444041fe145efa75b3ef4edd87425a6205dcc47c235610b07b92960bf952c5e78485c236cdff9ccadbe6e96203b749375d1c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
